---
spring:
    profiles: default
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        url: ${DATABASE_URL}
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        initialSize: 5
        removeAbandoned: true
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: create-drop
---
spring:
    profiles: test
    database:
        driverClassName: org.h2.Driver
    datasource:
        url: "jdbc:h2:mem:"    
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: create-drop